version: '3.8'

services:
  neo4j:
    image: neo4j:5
    container_name: neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/neo4jtest123
      - NEO4J_server_memory_heap_max__size=2G
      - NEO4J_server_memory_heap_initial__size=2G
      - NEO4J_server_memory_pagecache_size=1G
    volumes:
      - neo4j_data:/data
      - ./scripts/init.cypher:/docker-entrypoint-initdb.d/init.cypher
    mem_limit: 4g
    cpus: 1.0

  baconometer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: baconometer
    ports:
      - "5000:5000"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=neo4jtest123
      - FLASK_APP=src/app.py
    depends_on:
      - neo4j
    volumes:
      - ./src:/app/src
    working_dir: /app
    # Enable auto-reload for development
    # Note: --reload is not available in production mode, so this is for development only.
    command: ["flask", "run", "--host=0.0.0.0", --reload]
    mem_limit: 1g
    cpus: 0.5

volumes:
  neo4j_data:
