version: '3.8'

services:
  neo4j:
    image: neo4j:5
    container_name: neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/neo4jtest123
    volumes:
      - neo4j_data:/data
    mem_limit: 2g
    cpus: 1.0

  baconometer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: baconometer
    ports:
      - "5000:5000"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=neo4jtest123
      - FLASK_APP=src/app.py
    depends_on:
      - neo4j
    volumes:
      - ./src:/app/src
    working_dir: /app
    command: ["flask", "run", "--host=0.0.0.0"]
    mem_limit: 1g
    cpus: 0.5

volumes:
  neo4j_data:
