services:
  seed:
    image: neo4j:5
    container_name: baconometer-seed
    entrypoint: ["neo4j-admin", "database", "import", "full", "neo4j",
      "--nodes=Actor=/import/actors.csv",
      "--nodes=Film=/import/films.csv",
      "--relationships=ACTED_IN=/import/acted_in.csv",
      "--overwrite-destination=true",
      ]
    volumes:
      - ./seed/actors.csv:/import/actors.csv
      - ./seed/films.csv:/import/films.csv
      - ./seed/acted_in.csv:/import/acted_in.csv
      - neo4j_data:/data
    mem_limit: 2g
    cpus: 1.0

volumes:
  neo4j_data:
